name:  GitHub Actions Unit Tests

on:
  push:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.7
    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        cd module/api
        pipenv install --ignore-pipfile
    - name: Run tests with pytest
      run: |
        cd module/api
        pipenv run shell
        PIPENV_DOTENV_LOCATION=/module/api pipenv run python -m pytest
